# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `activejob` gem.
# Please instead update this file by running `bin/tapioca gem activejob`.


# :markup: markdown
# :include: ../README.md
#
# pkg:gem/activejob#lib/active_job/serializers/object_serializer.rb:3
module ActiveJob; end

# = Active Job \Serializers
#
# The +ActiveJob::Serializers+ module is used to store a list of known serializers
# and to add new ones. It also has helpers to serialize/deserialize objects.
#
# pkg:gem/activejob#lib/active_job/serializers/object_serializer.rb:4
module ActiveJob::Serializers; end

# Base class for serializing and deserializing custom objects.
#
# Example:
#
#   class MoneySerializer < ActiveJob::Serializers::ObjectSerializer
#     def serialize(money)
#       super("amount" => money.amount, "currency" => money.currency)
#     end
#
#     def deserialize(hash)
#       Money.new(hash["amount"], hash["currency"])
#     end
#
#     private
#
#       def klass
#         Money
#       end
#   end
#
# pkg:gem/activejob#lib/active_job/serializers/object_serializer.rb:24
class ActiveJob::Serializers::ObjectSerializer
  include ::Singleton::SingletonInstanceMethods
  include ::Singleton
  extend ::Singleton::SingletonClassMethods

  # Deserializes an argument from a JSON primitive type.
  #
  # pkg:gem/activejob#lib/active_job/serializers/object_serializer.rb:42
  def deserialize(json); end

  # Serializes an argument to a JSON primitive type.
  #
  # pkg:gem/activejob#lib/active_job/serializers/object_serializer.rb:37
  def serialize(hash); end

  # Determines if an argument should be serialized by a serializer.
  #
  # pkg:gem/activejob#lib/active_job/serializers/object_serializer.rb:32
  def serialize?(argument); end

  private

  # The class of the object that will be serialized.
  #
  # pkg:gem/activejob#lib/active_job/serializers/object_serializer.rb:48
  def klass; end

  class << self
    # Deserializes an argument from a JSON primitive type.
    #
    # pkg:gem/activejob#lib/active_job/serializers/object_serializer.rb:28
    def deserialize(*_arg0, **_arg1, &_arg2); end

    # Serializes an argument to a JSON primitive type.
    #
    # pkg:gem/activejob#lib/active_job/serializers/object_serializer.rb:28
    def serialize(*_arg0, **_arg1, &_arg2); end

    # Determines if an argument should be serialized by a serializer.
    #
    # pkg:gem/activejob#lib/active_job/serializers/object_serializer.rb:28
    def serialize?(*_arg0, **_arg1, &_arg2); end

    private

    # pkg:gem/activejob#lib/active_job/serializers/object_serializer.rb:25
    def allocate; end

    # pkg:gem/activejob#lib/active_job/serializers/object_serializer.rb:25
    def new(*_arg0); end
  end
end
