name: Publish
permissions:
  contents: read
  id-token: write
on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  rubocop:
    uses: ./.github/workflows/rubocop.yml
  sorbet:
    uses: ./.github/workflows/sorbet.yml
  test:
    uses: ./.github/workflows/test.yml
  zeitwerk:
    uses: ./.github/workflows/zeitwerk.yml
  publish:
    runs-on: ubuntu-latest
    needs: [rubocop, sorbet, test, zeitwerk]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - uses: rubygems/release-gem@v1
